on: 
  push:
    tags:
      - '*'

jobs:
  buildAndRelease:
    runs-on: ubuntu-latest
    name: A job to publish the static site to IPFS
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Use Node.js 8.x
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - name: Install dependencies
        run: npm install    
      - name: Test
        run: npm test
        env:
          CI: true
      - name: Generate build
        run: npm run build
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-build
          path: build
  deploy:
    runs-on: ubuntu-latest
    # When application is successfully tested and build has been generated
    # Then we can start with deployment
    needs: build
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: react-github-actions-build
    - name: publish
      uses: sha224/ipfs-publisher@v1
      env:
        DEFAULT_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PINATA_TOKEN: ${{ secrets.PINATA_TOKEN }}
        CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}
        CLOUDFLARE_ZONEID: ${{ secrets.CLOUDFLARE_ZONEID }}
  release:
    runs-on: ubuntu-latest
    # We specify that deploys needs to
    # finish before we create a release
    needs: deploy
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: react-github-actions-build
      # Zip the build using external action
      - name: Zip build
        uses: thedoctor0/zip-release@master
        with:
          filename: react-github-actions-release-build.zip
          path: react-github-actions-build
      # Upload as an artifact of the current workflow
      - name: Upload build zip artifact
        uses: actions/upload-artifact@v1
        with:
          name: react-github-actions-release-build.zip
          path: react-github-actions-release-build.zip
      # Make official GitHub release which will trigger
      # sending the mail with link for access
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: react-github-actions-release-build.zip
          body: ${{ secrets.CLOUDFLARE_ZONEID }} updated
          token: ${{ secrets.GITHUB_TOKEN }}
